// Code generated by MockGen. DO NOT EDIT.
// Source: internal/crypto/base.go

// Package crypto is a generated GoMock package.
package crypto

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCipher is a mock of Cipher interface.
type MockCipher struct {
	ctrl     *gomock.Controller
	recorder *MockCipherMockRecorder
}

// MockCipherMockRecorder is the mock recorder for MockCipher.
type MockCipherMockRecorder struct {
	mock *MockCipher
}

// NewMockCipher creates a new mock instance.
func NewMockCipher(ctrl *gomock.Controller) *MockCipher {
	mock := &MockCipher{ctrl: ctrl}
	mock.recorder = &MockCipherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCipher) EXPECT() *MockCipherMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockCipher) Decrypt(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockCipherMockRecorder) Decrypt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockCipher)(nil).Decrypt), arg0)
}

// Encrypt mocks base method.
func (m *MockCipher) Encrypt(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockCipherMockRecorder) Encrypt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockCipher)(nil).Encrypt), arg0)
}

// MockCipherFactory is a mock of CipherFactory interface.
type MockCipherFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCipherFactoryMockRecorder
}

// MockCipherFactoryMockRecorder is the mock recorder for MockCipherFactory.
type MockCipherFactoryMockRecorder struct {
	mock *MockCipherFactory
}

// NewMockCipherFactory creates a new mock instance.
func NewMockCipherFactory(ctrl *gomock.Controller) *MockCipherFactory {
	mock := &MockCipherFactory{ctrl: ctrl}
	mock.recorder = &MockCipherFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCipherFactory) EXPECT() *MockCipherFactoryMockRecorder {
	return m.recorder
}

// NewCipher mocks base method.
func (m *MockCipherFactory) NewCipher(arg0 string) Cipher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCipher", arg0)
	ret0, _ := ret[0].(Cipher)
	return ret0
}

// NewCipher indicates an expected call of NewCipher.
func (mr *MockCipherFactoryMockRecorder) NewCipher(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCipher", reflect.TypeOf((*MockCipherFactory)(nil).NewCipher), arg0)
}

// MockFileReaderWriter is a mock of FileReaderWriter interface.
type MockFileReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockFileReaderWriterMockRecorder
}

// MockFileReaderWriterMockRecorder is the mock recorder for MockFileReaderWriter.
type MockFileReaderWriterMockRecorder struct {
	mock *MockFileReaderWriter
}

// NewMockFileReaderWriter creates a new mock instance.
func NewMockFileReaderWriter(ctrl *gomock.Controller) *MockFileReaderWriter {
	mock := &MockFileReaderWriter{ctrl: ctrl}
	mock.recorder = &MockFileReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileReaderWriter) EXPECT() *MockFileReaderWriterMockRecorder {
	return m.recorder
}

// ReadFile mocks base method.
func (m *MockFileReaderWriter) ReadFile(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockFileReaderWriterMockRecorder) ReadFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockFileReaderWriter)(nil).ReadFile), arg0)
}

// WriteFile mocks base method.
func (m *MockFileReaderWriter) WriteFile(arg0 string, arg1 []byte, arg2 os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockFileReaderWriterMockRecorder) WriteFile(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockFileReaderWriter)(nil).WriteFile), arg0, arg1, arg2)
}
