name: Checkout code and Setup Go
description: 'Checkout code and setup Go version 1.20'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      shell: bash

    - name: Set up Go
      shell: bash
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
